-- V16: Create timezones lookup table
-- Stores the canonical list of IANA timezone identifiers.
-- display_order controls the order returned to the frontend.
-- is_active allows soft-disabling a timezone without breaking existing user rows.

CREATE TABLE timezones
(
    id            SERIAL PRIMARY KEY,
    name          VARCHAR(64)  NOT NULL UNIQUE,
    display_order SMALLINT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO timezones (name, display_order) VALUES
    ('UTC',                    1),
    ('America/New_York',       2),
    ('America/Chicago',        3),
    ('America/Denver',         4),
    ('America/Phoenix',        5),
    ('America/Los_Angeles',    6),
    ('America/Anchorage',      7),
    ('America/Honolulu',       8),
    ('America/Sao_Paulo',      9),
    ('America/Argentina/Buenos_Aires', 10),
    ('America/Bogota',         11),
    ('America/Lima',           12),
    ('America/Santiago',       13),
    ('America/Mexico_City',    14),
    ('America/Toronto',        15),
    ('America/Vancouver',      16),
    ('Europe/London',          17),
    ('Europe/Dublin',          18),
    ('Europe/Lisbon',          19),
    ('Europe/Paris',           20),
    ('Europe/Berlin',          21),
    ('Europe/Rome',            22),
    ('Europe/Madrid',          23),
    ('Europe/Amsterdam',       24),
    ('Europe/Brussels',        25),
    ('Europe/Zurich',          26),
    ('Europe/Stockholm',       27),
    ('Europe/Oslo',            28),
    ('Europe/Copenhagen',      29),
    ('Europe/Helsinki',        30),
    ('Europe/Warsaw',          31),
    ('Europe/Prague',          32),
    ('Europe/Vienna',          33),
    ('Europe/Budapest',        34),
    ('Europe/Bucharest',       35),
    ('Europe/Athens',          36),
    ('Europe/Istanbul',        37),
    ('Europe/Moscow',          38),
    ('Asia/Dubai',             39),
    ('Asia/Karachi',           40),
    ('Asia/Kolkata',           41),
    ('Asia/Colombo',           42),
    ('Asia/Dhaka',             43),
    ('Asia/Kathmandu',         44),
    ('Asia/Almaty',            45),
    ('Asia/Tashkent',          46),
    ('Asia/Yekaterinburg',     47),
    ('Asia/Bangkok',           48),
    ('Asia/Ho_Chi_Minh',       49),
    ('Asia/Jakarta',           50),
    ('Asia/Singapore',         51),
    ('Asia/Kuala_Lumpur',      52),
    ('Asia/Manila',            53),
    ('Asia/Shanghai',          54),
    ('Asia/Hong_Kong',         55),
    ('Asia/Taipei',            56),
    ('Asia/Seoul',             57),
    ('Asia/Tokyo',             58),
    ('Asia/Novosibirsk',       59),
    ('Asia/Krasnoyarsk',       60),
    ('Asia/Irkutsk',           61),
    ('Asia/Yakutsk',           62),
    ('Asia/Vladivostok',       63),
    ('Australia/Perth',        64),
    ('Australia/Darwin',       65),
    ('Australia/Adelaide',     66),
    ('Australia/Brisbane',     67),
    ('Australia/Sydney',       68),
    ('Australia/Melbourne',    69),
    ('Pacific/Auckland',       70),
    ('Pacific/Fiji',           71),
    ('Pacific/Honolulu',       72),
    ('Africa/Cairo',           73),
    ('Africa/Johannesburg',    74),
    ('Africa/Lagos',           75),
    ('Africa/Nairobi',         76);
